/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 429fc37d0b352a88072245a17d18a60f)
// Runtime types generated with workerd@1.20250712.0 2025-02-14 nodejs_compat
declare namespace Cloudflare {
	interface Env {
		TURSO_DATABASE_URL: string;
		TURSO_AUTH_TOKEN?: string;
		SUPER_ADMIN_TOKEN: '123';
		pages_build_output_dir: 'public';
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env { }

// Begin runtime types
/*! *****************************************************************************
Copyright (c) Cloudflare. All rights reserved.
Copyright (c) Microsoft Corporation. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0
THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.
See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
/* eslint-disable */
// noinspection JSUnusedGlobalSymbols
declare var onmessage: never;
/**
 * An abnormal event (called an exception) which occurs as a result of calling a method or accessing a property of a web API.
 *
 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException)
 */
declare class DOMException extends Error {
	constructor(message?: string, name?: string);
	/* [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException/message) */
	readonly message: string;
	/* [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException/name) */
	readonly name: string;
	/**
	 * @deprecated
	 *
	 * [MDN Reference](https://developer.mozilla.org/docs/Web/API/DOMException/code)
	 */
	readonly code: number;
	static readonly INDEX_SIZE_ERR: number;
	static readonly DOMSTRING_SIZE_ERR: number;
	static readonly HIERARCHY_REQUEST_ERR: number;
	static readonly WRONG_DOCUMENT_ERR: number;
	static readonly INVALID_CHARACTER_ERR: number;
	static readonly NO_DATA_ALLOWED_ERR: number;
	static readonly NO_MODIFICATION_ALLOWED_ERR: number;
	static readonly NOT_FOUND_ERR: number;
	static readonly NOT_SUPPORTED_ERR: number;
	static readonly INUSE_ATTRIBUTE_ERR: number;
	static readonly INVALID_STATE_ERR: number;
	static readonly SYNTAX_ERR: number;
	static readonly INVALID_MODIFICATION_ERR: number;
	static readonly NAMESPACE_ERR: number;
	static readonly INVALID_ACCESS_ERR: number;
	static readonly VALIDATION_ERR: number;
	static readonly TYPE_MISMATCH_ERR: number;
	static readonly SECURITY_ERR: number;
	static readonly NETWORK_ERR: number;
	static readonly ABORT_ERR: number;
	static readonly URL_MISMATCH_ERR: number;
	static readonly QUOTA_EXCEEDED_ERR: number;
	static readonly TIMEOUT_ERR: number;
	static readonly INVALID_NODE_TYPE_ERR: number;
	static readonly DATA_CLONE_ERR: number;
	get stack(): any;
	set stack(value: any);
}
type WorkerGlobalScopeEventMap = {
	fetch: FetchEvent;
	scheduled: ScheduledEvent;
	queue: QueueEvent;
	unhandledrejection: PromiseRejectionEvent;
	rejectionhandled: PromiseRejectionEvent;
};
declare abstract class WorkerGlobalScope extends EventTarget<WorkerGlobalScopeEventMap> {
	EventTarget: typeof EventTarget;
}
/* [MDN Reference](https://developer.mozilla.org/docs/Web/API/console) */
interface Console {
	'assert'(condition?: boolean, ...data: any[]): void;
	/* [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/clear_static) */
	clear(): void;
	/* [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/count_static) */
	count(label?: string): void;
	/* [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/countReset_static) */
	countReset(label?: string): void;
	/* [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/debug_static) */
	debug(...data: any[]): void;
	/* [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/dir_static) */
	dir(item?: any, options?: any): void;
	/* [MDN Reference](https://developer.mozilla.org/docs/Web/API/console/dirxml_static) */
}
