// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env { 
	KV_BINDING: KVNamespace;      // Cloudflare KV 命名空间 
    DB_USER: string;
}
