# 开发模式 Wrangler 配置
name = "node-fetch-dev"
main = "src/index.ts"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]

# 开发配置
[vars]
NODE_ENV = "development"

# KV 绑定
[[kv_namespaces]]
binding = "KV_BINDING"
id = "52fa82d5a9c3438195385f592be41ef9"

[[kv_namespaces]]
binding = "USERS_KV"
id = "52fa82d5a9c3438195385f592be41ef9"

# 开发模式特定配置
[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "https"

# 静态文件配置
[assets]
directory = "public" 